# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfc89c7225d282858efd1545e55e1ecbc4d96895c2c64b21f75b76f3b69980fff80c2857e17ac0f09d911c774accc895600ccfa5d8ef6a5f9993948510cdd37b

test:
  secret_key_base: d9b5325526f4339b5edb05c5b08a85b29c1e668e69313c08dc742b4cb4e1b3cb6dd88dd79a66dfca7772238d7376d69e20f353180e94d5dd16af741a54eb89a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
